apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: foodiesreplicaset
  labels:
    app: foodies
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: foodies
      version: "1.0"  
  template:
    metadata:
      name: foodiespod
      labels:
        app: foodies
        version: "1.0"
    spec: 
      containers:
        - name: foodies
          image: mohommadali/foodiesreplicaset:1.0
          ports: 
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
              path: /fodies/actuator/health/readiness
            initialDelaySeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /fodies/actuator/health/liveness
            initialDelaySeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3
                          















